import type { Config } from 'tailwindcss';
import tailwindcssAnimate from 'tailwindcss-animate';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    extend: {
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1400px',
      },
      fontFamily: {
        sans: ['var(--font-abc-diatype)', 'system-ui', 'sans-serif'],
        romie: ['var(--font-romie)', 'serif'],
        diatype: ['var(--font-abc-diatype)', 'system-ui', 'sans-serif'],
      },
      zIndex: {
        999999: '999999',
        99999: '99999',
        9999: '9999',
        999: '999',
        99: '99',
        9: '9',
        1: '1',
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        5: '20px',
        6: '24px',
        7: '28px',
        9: '36px',
        10: '40px',
        11: '44px',
        14: '56px',
        16: '64px',
        18: '4.5rem',
        28: '112px',
        40: '160px',
        44: '176px',
        48: '192px',
        52: '208px',
        56: '224px',
        60: '240px',
        64: '256px',
        72: '288px',
        80: '320px',
        96: '384px',
      },
      colors: {
        white: '#FFFFFF',
        black: '#000000',
        'text-title': '#FFF',
        'text-error': '#F36B6D',
        ui: {
          neutralSurfaceBackground: '#EEEEEE',
          neutralSurfaceOnColor: '#1F1F1F',
          neutralContentBody: '#838282',
          neutralSurfaceSupport: '#D8D8D8',
          neutralBorderComponent: '#E1E1E1',
          neutralPlaceholder: '#A2A1A1',
          neutralDarkRed: '#9D0D11',
          neuteralSurfaceSecondary: '#CDBAB1',
          neutralContentLight: '#B5B5B5',
          neutralBorderActive: '#1B1C1E',
          neutralInputBg: '#F2F2F2',
          neutralBgDisabled: '#EAEAEA',
          textError: '#9D0D11',
          errorBgLight: 'hsl(var(--error-bg-light))',
          errorBorder: '#E2B6B8',
          componentsAlertWarningBackground: '#FFF4E5',
          backgroundBg: '#E6E6E6',
          colorContentSuccess: '#167E60',
          neutralBorderTables: '#D4D4D4',
          textLightBlue: '#0D729D',
          bgLightBlue: '#E7F1F5',
          bgLightRed: '#F5E7E7',
          disabledIconsColor: '#9C9C9C',
          neutralBorderDisabled: '#BFBFBF',
          neutralBorderSupport: '#E1E3E6',
          textTertiary: '#696969',
          lightGreyBorder: '#DCDCDC',
          alertColor: '#F1B422',
          bgBlur: '#A4887E',
          errorBorderColor: '#D32F2F',
          textPrimaryColor: '#393D3F',
        },
        heading: {
          black: '#1D2126',
          lightblack: '#5C6167',
        },
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        none: '0',
        sm: '2px',
        '4': '4px',
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '28': '28px',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
      },
      boxShadow: {
        s100: '0px 1px 1px 0px var(--shadow-s100), 0px 0px 1px 0px var(--shadow-default)',
        s200: '0px 3px 5px 0px var(--shadow-s200), 0px 0px 1px 0px var(--shadow-default)',
        s300: '0px 8px 12px 0px var(--shadow-s300), 0px 0px 1px 0px var(--shadow-default)',
        s400: '0px 10px 18px 0px var(--shadow-s400), 0px 0px 1px 0px var(--shadow-default)',
        s500: '0px 18px 28px 0px var(--shadow-s500), 0px 0px 1px 0px var(--shadow-default)',
        'text-error': '0px 4px 4px rgba(0, 0, 0, 0.25)',
      },
      fontSize: {
        'display-1': ['72px', { lineHeight: '104px', fontWeight: '800' }],
        'display-2': ['64px', { lineHeight: '88px', fontWeight: '800' }],
        'display-3': ['56px', { lineHeight: '72px', fontWeight: '800' }],
        h1: ['48px', { lineHeight: '64px', fontWeight: '700' }],
        h2: ['40px', { lineHeight: '56px', fontWeight: '700' }],
        h3: ['36px', { lineHeight: '48px', fontWeight: '700' }],
        'h3-lighter': ['36px', { lineHeight: '48px', fontWeight: '600' }],
        h4: ['32px', { lineHeight: '44px', fontWeight: '700' }],
        h5: ['24px', { lineHeight: '32px', fontWeight: '700' }],
        h6: ['18px', { lineHeight: '28px', fontWeight: '700' }],
        title: ['14px', { lineHeight: '22px', fontWeight: '600' }],
        'title-text': ['20px', { lineHeight: '24px', fontWeight: '600' }],
        offer: ['14px', { lineHeight: '16px', fontWeight: '400' }],
        regular: ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'regular-bolder': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'regular-normal': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'error-caption': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        subtitle: ['13px', { lineHeight: '20px', fontWeight: '600' }],
        link: ['14px', { lineHeight: '20px' }],
        'text-primary': ['14px', { lineHeight: '22px', fontWeight: '500' }],
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
        'circle-completion': {
          '0%': {
            strokeDashoffset: '251.2',
          },
          '100%': {
            strokeDashoffset: '0',
          },
        },
        checkmark: {
          '0%': {
            opacity: '0',
            transform: 'scale(0)',
          },
          '100%': {
            opacity: '1',
            transform: 'scale(1)',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'circle-completion': 'circle-completion 1s ease-in-out forwards',
        checkmark: 'checkmark 0.5s ease-in-out 0.7s forwards',
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        md: '1.5rem',
        lg: '2rem',
      },
    },
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1400px',
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
